//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PreSplitCamionetas.WebServiceEmbarquesLocal {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceEmbarquesSoap", Namespace="http://189.206.160.206:81/WebServiceEmbarques")]
    public partial class WebServiceEmbarques : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarPosibleDiferenciaEmbarquesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivarbotonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivarHoraInicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionAguilaresOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionUbicacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailPersonalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceEmbarques() {
            this.Url = "http://192.168.123.4:81/EmbarquesApk/WebServiceEmbarques/WebServiceEmbarques.asmx" +
                "";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event EnviarPosibleDiferenciaEmbarquesCompletedEventHandler EnviarPosibleDiferenciaEmbarquesCompleted;
        
        /// <remarks/>
        public event SendMailCompletedEventHandler SendMailCompleted;
        
        /// <remarks/>
        public event ActivarbotonCompletedEventHandler ActivarbotonCompleted;
        
        /// <remarks/>
        public event ActivarHoraInicioCompletedEventHandler ActivarHoraInicioCompleted;
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        public event VersionAguilaresCompletedEventHandler VersionAguilaresCompleted;
        
        /// <remarks/>
        public event VersionUbicacionesCompletedEventHandler VersionUbicacionesCompleted;
        
        /// <remarks/>
        public event SendMailPersonalCompletedEventHandler SendMailPersonalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/HelloWorld", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/EnviarPosibleDiferenciaEmbarques", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EnviarPosibleDiferenciaEmbarques(string id_embarque, string Tipo) {
            object[] results = this.Invoke("EnviarPosibleDiferenciaEmbarques", new object[] {
                        id_embarque,
                        Tipo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarPosibleDiferenciaEmbarquesAsync(string id_embarque, string Tipo) {
            this.EnviarPosibleDiferenciaEmbarquesAsync(id_embarque, Tipo, null);
        }
        
        /// <remarks/>
        public void EnviarPosibleDiferenciaEmbarquesAsync(string id_embarque, string Tipo, object userState) {
            if ((this.EnviarPosibleDiferenciaEmbarquesOperationCompleted == null)) {
                this.EnviarPosibleDiferenciaEmbarquesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarPosibleDiferenciaEmbarquesOperationCompleted);
            }
            this.InvokeAsync("EnviarPosibleDiferenciaEmbarques", new object[] {
                        id_embarque,
                        Tipo}, this.EnviarPosibleDiferenciaEmbarquesOperationCompleted, userState);
        }
        
        private void OnEnviarPosibleDiferenciaEmbarquesOperationCompleted(object arg) {
            if ((this.EnviarPosibleDiferenciaEmbarquesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarPosibleDiferenciaEmbarquesCompleted(this, new EnviarPosibleDiferenciaEmbarquesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/SendMail", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMail(string Dest, string mBody, string mAsunto) {
            this.Invoke("SendMail", new object[] {
                        Dest,
                        mBody,
                        mAsunto});
        }
        
        /// <remarks/>
        public void SendMailAsync(string Dest, string mBody, string mAsunto) {
            this.SendMailAsync(Dest, mBody, mAsunto, null);
        }
        
        /// <remarks/>
        public void SendMailAsync(string Dest, string mBody, string mAsunto, object userState) {
            if ((this.SendMailOperationCompleted == null)) {
                this.SendMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailOperationCompleted);
            }
            this.InvokeAsync("SendMail", new object[] {
                        Dest,
                        mBody,
                        mAsunto}, this.SendMailOperationCompleted, userState);
        }
        
        private void OnSendMailOperationCompleted(object arg) {
            if ((this.SendMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/Activarboton", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Activarboton() {
            object[] results = this.Invoke("Activarboton", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivarbotonAsync() {
            this.ActivarbotonAsync(null);
        }
        
        /// <remarks/>
        public void ActivarbotonAsync(object userState) {
            if ((this.ActivarbotonOperationCompleted == null)) {
                this.ActivarbotonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivarbotonOperationCompleted);
            }
            this.InvokeAsync("Activarboton", new object[0], this.ActivarbotonOperationCompleted, userState);
        }
        
        private void OnActivarbotonOperationCompleted(object arg) {
            if ((this.ActivarbotonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivarbotonCompleted(this, new ActivarbotonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/ActivarHoraInicio", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActivarHoraInicio() {
            object[] results = this.Invoke("ActivarHoraInicio", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivarHoraInicioAsync() {
            this.ActivarHoraInicioAsync(null);
        }
        
        /// <remarks/>
        public void ActivarHoraInicioAsync(object userState) {
            if ((this.ActivarHoraInicioOperationCompleted == null)) {
                this.ActivarHoraInicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivarHoraInicioOperationCompleted);
            }
            this.InvokeAsync("ActivarHoraInicio", new object[0], this.ActivarHoraInicioOperationCompleted, userState);
        }
        
        private void OnActivarHoraInicioOperationCompleted(object arg) {
            if ((this.ActivarHoraInicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivarHoraInicioCompleted(this, new ActivarHoraInicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/Version", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version() {
            object[] results = this.Invoke("Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync() {
            this.VersionAsync(null);
        }
        
        /// <remarks/>
        public void VersionAsync(object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[0], this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/VersionAguilares", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VersionAguilares() {
            object[] results = this.Invoke("VersionAguilares", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAguilaresAsync() {
            this.VersionAguilaresAsync(null);
        }
        
        /// <remarks/>
        public void VersionAguilaresAsync(object userState) {
            if ((this.VersionAguilaresOperationCompleted == null)) {
                this.VersionAguilaresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionAguilaresOperationCompleted);
            }
            this.InvokeAsync("VersionAguilares", new object[0], this.VersionAguilaresOperationCompleted, userState);
        }
        
        private void OnVersionAguilaresOperationCompleted(object arg) {
            if ((this.VersionAguilaresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionAguilaresCompleted(this, new VersionAguilaresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/VersionUbicaciones", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VersionUbicaciones() {
            object[] results = this.Invoke("VersionUbicaciones", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionUbicacionesAsync() {
            this.VersionUbicacionesAsync(null);
        }
        
        /// <remarks/>
        public void VersionUbicacionesAsync(object userState) {
            if ((this.VersionUbicacionesOperationCompleted == null)) {
                this.VersionUbicacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionUbicacionesOperationCompleted);
            }
            this.InvokeAsync("VersionUbicaciones", new object[0], this.VersionUbicacionesOperationCompleted, userState);
        }
        
        private void OnVersionUbicacionesOperationCompleted(object arg) {
            if ((this.VersionUbicacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionUbicacionesCompleted(this, new VersionUbicacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceEmbarques/SendMailPersonal", RequestNamespace="http://189.206.160.206:81/WebServiceEmbarques", ResponseNamespace="http://189.206.160.206:81/WebServiceEmbarques", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMailPersonal(string Dest, string mBody, string mAsunto, string usuario, string contraseña, string direccioncorreo) {
            this.Invoke("SendMailPersonal", new object[] {
                        Dest,
                        mBody,
                        mAsunto,
                        usuario,
                        contraseña,
                        direccioncorreo});
        }
        
        /// <remarks/>
        public void SendMailPersonalAsync(string Dest, string mBody, string mAsunto, string usuario, string contraseña, string direccioncorreo) {
            this.SendMailPersonalAsync(Dest, mBody, mAsunto, usuario, contraseña, direccioncorreo, null);
        }
        
        /// <remarks/>
        public void SendMailPersonalAsync(string Dest, string mBody, string mAsunto, string usuario, string contraseña, string direccioncorreo, object userState) {
            if ((this.SendMailPersonalOperationCompleted == null)) {
                this.SendMailPersonalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailPersonalOperationCompleted);
            }
            this.InvokeAsync("SendMailPersonal", new object[] {
                        Dest,
                        mBody,
                        mAsunto,
                        usuario,
                        contraseña,
                        direccioncorreo}, this.SendMailPersonalOperationCompleted, userState);
        }
        
        private void OnSendMailPersonalOperationCompleted(object arg) {
            if ((this.SendMailPersonalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailPersonalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EnviarPosibleDiferenciaEmbarquesCompletedEventHandler(object sender, EnviarPosibleDiferenciaEmbarquesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarPosibleDiferenciaEmbarquesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarPosibleDiferenciaEmbarquesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendMailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ActivarbotonCompletedEventHandler(object sender, ActivarbotonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivarbotonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivarbotonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ActivarHoraInicioCompletedEventHandler(object sender, ActivarHoraInicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivarHoraInicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivarHoraInicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VersionAguilaresCompletedEventHandler(object sender, VersionAguilaresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionAguilaresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionAguilaresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VersionUbicacionesCompletedEventHandler(object sender, VersionUbicacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionUbicacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionUbicacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendMailPersonalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591